donate/urls.py
from django.urls import path
from . import views
#url patterns
app_name = 'donate'

urlpatterns = [
    path('',views.index,name='index'),
    path('donation-details/',views.donation_detail,name='donation-details'),
    path('donate/',views.donate,name='donate'),
    path('summary/',views.payment_completion,name='summary'),
    path('list/',views.Contributors.as_view(),name='list')
]

sattardas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('donate.urls')),
]

donate/models.py
from django.db import models

# Create your models here.
class Donation(models.Model):
    name = models.CharField(max_length=100)
    amount = models.IntegerField()

donate/forms.py
from django import forms
from .models import Donation
#form classes

class DonorCreateForm(forms.ModelForm):
   
   class Meta:
       model = Donation
       fields = ['name','amount']

donate/views.py
from django.shortcuts import render
from django.views.generic import list
from django.http import HttpResponse
from .forms import DonorCreateForm
from .models import Donation
# Create your views here.

import razorpay
#create the client
client = razorpay.Client(auth=('rzp_test_yPkkDyRXgbHxNk','5plGK3VWOznXLpD6lZdseLfi'))

#home page
def index(request):
    return render(request,'donate/index.html')

def donation_detail(request):
    form = DonorCreateForm()
    return render(request,'donate/donation_details.html',{'form':form})

#donation page
def donate(request):

    if request.method == 'POST':

        form = DonorCreateForm(request.POST)

        if form.is_valid():
            #get the form data
            amount = int(form.cleaned_data['amount'])
            name = form.cleaned_data['name']

            #create order
            response = client.order.create(dict(amount=amount*100,currency='INR'))

            #get the order details
            order_id = response['id']
            order_status = response['status']

            #if the order is successfully created
            if order_status=='created':
                form.save()
                context={
                    'name':name,
                    'amount':amount,
                    'order_id':order_id,
                    }
                return render(request,'donate/donate.html',context)
            else:
                return HttpResponse('<h1>Error in  create order function</h1>')


#order summary page
def payment_completion(request):
    
    response = request.POST

    params_dict = {
        'razorpay_payment_id' : response['razorpay_payment_id'],
        'razorpay_order_id' : response['razorpay_order_id'],
        'razorpay_signature' : response['razorpay_signature']
    }

    # verify payment
    try:
        status = client.utility.verify_payment_signature(params_dict)
        return render(request, 'donate/order_summary.html', {'status': 'Payment Successful'})
    except:
        return render(request, 'donate/order_summary.html', {'status': 'Payment Faliure!!!'})

class Contributors(list.ListView):
    model = Donation
    context_object_name = 'donors'
    template_name = 'donate/list.html'

donate/templates/donate/donate.html
{% extends 'base.html' %}

{% block content %}
<h1>Thanks for taking the time to donate!!</h1>

<div class="jumbotron">
    <form action="{% url 'donate:summary' %}" method="POST">{% csrf_token %}
        <script    
                src="https://checkout.razorpay.com/v1/checkout.js"    
                data-key="rzp_test_yPkkDyRXgbHxNk" // Key ID generated from the Dashboard    
                data-amount="{{ amount }}" 
                data-currency="INR"    
                data-order_id="{{ order_id }}"
                data-buttontext="Pay with Razorpay"    
                data-name="Acme Corp"    
                data-description="Test transaction"    
                data-prefill.name="{{ name }}"      
                data-theme.color="#F37254"></script>
        <input type="hidden" custom="Hidden Element" name="hidden">
    </form>
</div>
{% endblock %}

donate/templates/donate/donation_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron">
    <form action="{% url 'donate:donate' %}" method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value='donate'>
    </form>
    </div>
{% endblock %}

donate/templates/donate/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to Sattardas Donation Page</h1>
    <h2><a href="{% url 'donate:donation-details' %}">Click Here to donate</a></h2>
{% endblock %}

donate/templates/donate/list.html
{% extends 'base.html' %}

{% block content %}
<h1>List of Contributors</h1>
{% for donor in donors %}

    <h2>{{ donor.name }}</h2>
{% endfor %}

{% endblock %}

donate/templates/donate/order_summary.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ status }}</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sattardas</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'donate:index' %}">Sattardas Donate</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'donate:donation-details' %}">Donate</a>
            <a class="nav-item nav-link active" href="{% url 'donate:list' %}">Contributors</a>
          </div>
        </div>
      </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>